### ISSUE TITLE
Concurrency bug

### ISSUE THREAD

**Issue by karthik-enable** [ananthgoyal/AUTHZ_V2#5]
https://github.com/ananthgoyal/AUTHZ_V2/blob/ed040662888203a7bc35636b4c402e70cc41944c/src/backend/app/crud/crud_permission.py#L57

If 2 concurrent requests enter the same line i.e. pull the version number and the verify they both can pass this conditional check and still overwrite each other's data. See how versioning has to be correctly implemented ( check hibernate )

**Comment by ananthgoyal** [comment]
fixed using sqlalchemy version locking. The actual version object is mapped to version_col_id which auto updates version and locks during update process.
